version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout:
          path: ddlc-jp-src/
      - run:
          name: ツールのダウンロード
          command: apt update && apt install wget curl jq zip unzip -y
      - run:
          name: Ren'Py 6.99.12.4 ダウンロード
          command: |
            wget -O - https://www.renpy.org/dl/6.99.12.4/renpy-6.99.12.4-sdk.tar.bz2 | tar jxf -
            mv renpy-6.99.12.4-sdk renpy
      - run:
          name: DDLC v1.1.1 ダウンロード
          command: |
            wget -O ddlc.zip `curl -sX POST https://teamsalvato.itch.io/ddlc/file/594897 | jq -r .url`
            unzip ddlc.zip
            rm ddlc.zip
            mv DDLC-1.1.1-pc ddlc
      - run:
          name: パッチのビルド
          command: |
            cp -fpr ddlc-jp-src/* ddlc/
            ./renpy/renpy.sh ./ddlc/ lint
            ./renpy/renpy.sh ./renpy/launcher distribute ./ddlc/ --package pc --packagedest temp
      - run:
          name: ビルドの成果物から必要なファイルのみを取り出して圧縮
          command: |
            mkdir DDLC_JP DDLC_JP/game
            cp ddlc-jp-src/README_jp.html DDLC_JP/
            cp ddlc-jp-src/readme\ \(jp\ patch\).txt DDLC_JP/
            unzip temp.zip
            cp DDLC_JP-pc/game/jp.rpa DDLC_JP/game/
            cp DDLC_JP-pc/game/none.rpa DDLC_JP/game/
            zip -r DDLC_JP DDLC_JP
      - store_artifacts:
          path: DDLC_JP.zip
