version: 2.1

jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout:
          path: ddlc-jp-src/
      - run:
          name: ツールのダウンロード
          command: apt update && apt install wget curl jq zip unzip -y
      - run:
          name: Ren'Py 6.99.12.4 ダウンロード
          command: |
            wget -O - https://www.renpy.org/dl/6.99.12.4/renpy-6.99.12.4-sdk.tar.bz2 | tar jxf -
            mv renpy-6.99.12.4-sdk renpy
      - run:
          name: DDLC v1.1.1 ダウンロード
          command: |
            wget -O ddlc.zip `curl -sX POST https://teamsalvato.itch.io/ddlc/file/594897 | jq -r .url`
            unzip ddlc.zip
            rm ddlc.zip
            mv DDLC-1.1.1-pc ddlc
      - run:
          name: パッチのビルド
          command: |
            cp -fpr ddlc-jp-src/* ddlc/
            ./renpy/renpy.sh ./ddlc/ lint
            ./renpy/renpy.sh ./renpy/launcher distribute ./ddlc/ --package MOD
            mv DDLC_JP-dists/ artifacts/
      - store_artifacts:
          path: artifacts
      - persist_to_workspace:
          root: .
          paths:
            - artifacts

  release:
    docker:
      - image: circleci/golang:1.8
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "フォルダ名を修正"
          command: |
            unzip artifacts/DDLC_JP-MOD.zip
            mv DDLC_JP-MOD DDLC_JP_${CIRCLE_TAG}
            zip -r DDLC_JP_${CIRCLE_TAG} DDLC_JP_${CIRCLE_TAG}
      - run:
          name: "GitHub Release に Zip をアップロード"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} \
              -n "ver${CIRCLE_TAG} for v1.1.1" -delete -draft ${CIRCLE_TAG} DDLC_JP_${CIRCLE_TAG}.zip

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
